/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ecosolucoes.ecotroca.views.usuario;

import br.com.ecosolucoes.ecotroca.models.Pessoa;
import br.com.ecosolucoes.ecotroca.models.Usuario;
import br.com.ecosolucoes.ecotroca.models.dao.PessoaDAO;
import br.com.ecosolucoes.ecotroca.models.dao.UsuarioDAO;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author ferna
 */
public class TelaExcluirUsuario extends javax.swing.JFrame {

    /**
     * Creates new form TelaPesquisarUsuario
     */
    public TelaExcluirUsuario() {
        super("Ativar ou Desativar Usuários");
        initComponents();
        this.setLocationRelativeTo(null);
        avisoLabel.setVisible(false);
        avisoLabel2.setVisible(false);
        excluirUsuarioButton.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscarPeloIdTextField = new javax.swing.JTextField();
        buscarPeloLoginTextField = new javax.swing.JTextField();
        buscarPeloIdButton = new javax.swing.JButton();
        buscarPeloLoginButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        emailTextField = new javax.swing.JTextField();
        loginTextField = new javax.swing.JTextField();
        perfilAcessoTextField = new javax.swing.JTextField();
        usuarioAtivoTextField = new javax.swing.JTextField();
        idTextField = new javax.swing.JTextField();
        excluirUsuarioButton = new javax.swing.JButton();
        avisoLabel = new javax.swing.JLabel();
        avisoLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(813, 484));
        setResizable(false);

        buscarPeloIdTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar usuário pelo ID"));

        buscarPeloLoginTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar usuário pelo nome de login"));

        buscarPeloIdButton.setText("Buscar");
        buscarPeloIdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPeloIdButtonActionPerformed(evt);
            }
        });

        buscarPeloLoginButton.setText("Buscar");
        buscarPeloLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPeloLoginButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        emailTextField.setEditable(false);
        emailTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("E-mail"));
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        loginTextField.setEditable(false);
        loginTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome de Login"));
        loginTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginTextFieldActionPerformed(evt);
            }
        });

        perfilAcessoTextField.setEditable(false);
        perfilAcessoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Perfil de Acesso"));
        perfilAcessoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfilAcessoTextFieldActionPerformed(evt);
            }
        });

        usuarioAtivoTextField.setEditable(false);
        usuarioAtivoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuário Ativo"));
        usuarioAtivoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioAtivoTextFieldActionPerformed(evt);
            }
        });

        idTextField.setEditable(false);
        idTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("ID do Usuário"));
        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });

        excluirUsuarioButton.setBackground(new java.awt.Color(194, 23, 23));
        excluirUsuarioButton.setText("Excluir usuário");
        excluirUsuarioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirUsuarioButtonActionPerformed(evt);
            }
        });

        avisoLabel.setForeground(java.awt.Color.red);
        avisoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avisoLabel.setText("ATENÇÃO! Isso irá deletar o registro do usuário no banco de dados.");

        avisoLabel2.setForeground(java.awt.Color.red);
        avisoLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avisoLabel2.setText("Esta ação não é recomendada, opte sempre por apenas desativar o usuário!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addComponent(excluirUsuarioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(perfilAcessoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(usuarioAtivoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(avisoLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(avisoLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioAtivoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(perfilAcessoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(avisoLabel)
                .addGap(11, 11, 11)
                .addComponent(avisoLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(excluirUsuarioButton, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 208, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buscarPeloLoginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscarPeloIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buscarPeloIdButton)
                            .addComponent(buscarPeloLoginButton))
                        .addGap(201, 201, 201))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buscarPeloIdTextField)
                    .addComponent(buscarPeloIdButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buscarPeloLoginTextField)
                    .addComponent(buscarPeloLoginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginTextFieldActionPerformed

    private void perfilAcessoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfilAcessoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perfilAcessoTextFieldActionPerformed

    private void usuarioAtivoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioAtivoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioAtivoTextFieldActionPerformed

    private void buscarPeloIdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPeloIdButtonActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(buscarPeloIdTextField.getText());
        Usuario usuario = UsuarioDAO.readUsuario(id);
        if (usuario != null) {
            JOptionPane.showMessageDialog(null, "Busca realizada com sucesso.");
            Pessoa pessoa = PessoaDAO.readPessoa(usuario.getIdPessoa());
            loginTextField.setText(usuario.getLogin());
            emailTextField.setText(pessoa.getEmail());
            idTextField.setText(String.valueOf(usuario.getId()));
            perfilAcessoTextField.setText(usuario.getPerfilAcesso().name());
            String strUsuarioAtivo;
            if (usuario.isUsuarioAtivo()) {strUsuarioAtivo = "Sim";} else {strUsuarioAtivo = "Não";}
            usuarioAtivoTextField.setText(strUsuarioAtivo);
            avisoLabel.setVisible(true);
            avisoLabel2.setVisible(true);
            excluirUsuarioButton.setVisible(true);
        }        
    }//GEN-LAST:event_buscarPeloIdButtonActionPerformed

    private void buscarPeloLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPeloLoginButtonActionPerformed
        // TODO add your handling code here:
        String login = buscarPeloLoginTextField.getText();
        Usuario usuario = UsuarioDAO.buscarUsuarioPeloLogin(login);
        if (usuario != null) {
            JOptionPane.showMessageDialog(null, "Busca realizada com sucesso.");
            Pessoa pessoa = PessoaDAO.readPessoa(usuario.getIdPessoa());
            loginTextField.setText(usuario.getLogin());
            emailTextField.setText(pessoa.getEmail());
            idTextField.setText(String.valueOf(usuario.getId()));
            perfilAcessoTextField.setText(usuario.getPerfilAcesso().name());
            String strUsuarioAtivo;
            if (usuario.isUsuarioAtivo()) {strUsuarioAtivo = "Sim";} else {strUsuarioAtivo = "Não";}
            usuarioAtivoTextField.setText(strUsuarioAtivo);
            avisoLabel.setVisible(true);
            avisoLabel2.setVisible(true);
            excluirUsuarioButton.setVisible(true);
        }        
    }//GEN-LAST:event_buscarPeloLoginButtonActionPerformed

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTextFieldActionPerformed

    private void excluirUsuarioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirUsuarioButtonActionPerformed
        // TODO add your handling code here:
        UsuarioDAO.deleteUsuario(Integer.parseInt(idTextField.getText()));
    }//GEN-LAST:event_excluirUsuarioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaExcluirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaExcluirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaExcluirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaExcluirUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaExcluirUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avisoLabel;
    private javax.swing.JLabel avisoLabel2;
    private javax.swing.JButton buscarPeloIdButton;
    private javax.swing.JTextField buscarPeloIdTextField;
    private javax.swing.JButton buscarPeloLoginButton;
    private javax.swing.JTextField buscarPeloLoginTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton excluirUsuarioButton;
    private javax.swing.JTextField idTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JTextField perfilAcessoTextField;
    private javax.swing.JTextField usuarioAtivoTextField;
    // End of variables declaration//GEN-END:variables
}
