/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ecosolucoes.ecotroca.views;

import br.com.ecosolucoes.ecotroca.models.Pessoa;
import br.com.ecosolucoes.ecotroca.models.Usuario;
import br.com.ecosolucoes.ecotroca.models.dao.PessoaDAO;
import br.com.ecosolucoes.ecotroca.models.dao.UsuarioDAO;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author ferna
 */
public class TelaPesquisarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form TelaPesquisarUsuario
     */
    public TelaPesquisarUsuario() {
        super("Pesquisar Usuários");
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscarPeloIdTextField = new javax.swing.JTextField();
        buscarPeloLoginTextField = new javax.swing.JTextField();
        buscarPeloIdButton = new javax.swing.JButton();
        buscarPeloLoginButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        nomeCompletoTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        dataNascimentoTextField = new javax.swing.JTextField();
        enderecoTextField = new javax.swing.JTextField();
        telefoneTextField = new javax.swing.JTextField();
        cpfTextField = new javax.swing.JTextField();
        loginTextField = new javax.swing.JTextField();
        perfilAcessoTextField = new javax.swing.JTextField();
        usuarioAtivoTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(813, 484));
        setMinimumSize(new java.awt.Dimension(813, 484));
        setResizable(false);

        buscarPeloIdTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar usuário pelo ID"));

        buscarPeloLoginTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar usuário pelo nome de login"));

        buscarPeloIdButton.setText("Buscar");
        buscarPeloIdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPeloIdButtonActionPerformed(evt);
            }
        });

        buscarPeloLoginButton.setText("Buscar");
        buscarPeloLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPeloLoginButtonActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nomeCompletoTextField.setEditable(false);
        nomeCompletoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome Completo"));

        emailTextField.setEditable(false);
        emailTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("E-mail"));

        dataNascimentoTextField.setEditable(false);
        dataNascimentoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Data de Nascimento"));

        enderecoTextField.setEditable(false);
        enderecoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        telefoneTextField.setEditable(false);
        telefoneTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefone"));

        cpfTextField.setEditable(false);
        cpfTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("CPF"));

        loginTextField.setEditable(false);
        loginTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome de Login"));
        loginTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginTextFieldActionPerformed(evt);
            }
        });

        perfilAcessoTextField.setEditable(false);
        perfilAcessoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Perfil de Acesso"));
        perfilAcessoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfilAcessoTextFieldActionPerformed(evt);
            }
        });

        usuarioAtivoTextField.setEditable(false);
        usuarioAtivoTextField.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuário Ativo"));
        usuarioAtivoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioAtivoTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enderecoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeCompletoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dataNascimentoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(telefoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cpfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(perfilAcessoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(usuarioAtivoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeCompletoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataNascimentoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enderecoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telefoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpfTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(perfilAcessoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usuarioAtivoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buscarPeloLoginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscarPeloIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buscarPeloIdButton)
                            .addComponent(buscarPeloLoginButton))
                        .addGap(201, 201, 201))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buscarPeloIdTextField)
                    .addComponent(buscarPeloIdButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buscarPeloLoginTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buscarPeloLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginTextFieldActionPerformed

    private void perfilAcessoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfilAcessoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perfilAcessoTextFieldActionPerformed

    private void usuarioAtivoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioAtivoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioAtivoTextFieldActionPerformed

    private void buscarPeloIdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPeloIdButtonActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(buscarPeloIdTextField.getText());
        Usuario usuario = UsuarioDAO.readUsuario(id);
        if (usuario != null) {
            JOptionPane.showMessageDialog(null, "Busca realizada com sucesso.");
            Pessoa pessoa = PessoaDAO.readPessoa(usuario.getIdPessoa());
            nomeCompletoTextField.setText(pessoa.getNome()+" "+pessoa.getSobrenome());
            emailTextField.setText(pessoa.getEmail());
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            String strDataNascimento = dateFormat.format(pessoa.getDataNascimento());
            dataNascimentoTextField.setText(strDataNascimento);
            enderecoTextField.setText(pessoa.getEndereco());
            telefoneTextField.setText(pessoa.getTelefone());
            cpfTextField.setText(pessoa.getCpf());
            loginTextField.setText(usuario.getLogin());
            perfilAcessoTextField.setText(usuario.getPerfilAcesso().name());
            String strUsuarioAtivo;
            if (usuario.isUsuarioAtivo()) {strUsuarioAtivo = "Sim";} else {strUsuarioAtivo = "Não";}
            usuarioAtivoTextField.setText(strUsuarioAtivo);
        }        
    }//GEN-LAST:event_buscarPeloIdButtonActionPerformed

    private void buscarPeloLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPeloLoginButtonActionPerformed
        // TODO add your handling code here:
        String login = buscarPeloLoginTextField.getText();
        Usuario usuario = UsuarioDAO.buscarUsuarioPeloLogin(login);
        if (usuario != null) {
            JOptionPane.showMessageDialog(null, "Busca realizada com sucesso.");
            Pessoa pessoa = PessoaDAO.readPessoa(usuario.getIdPessoa());
            nomeCompletoTextField.setText(pessoa.getNome()+" "+pessoa.getSobrenome());
            emailTextField.setText(pessoa.getEmail());
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            String strDataNascimento = dateFormat.format(pessoa.getDataNascimento());
            dataNascimentoTextField.setText(strDataNascimento);
            enderecoTextField.setText(pessoa.getEndereco());
            telefoneTextField.setText(pessoa.getTelefone());
            cpfTextField.setText(pessoa.getCpf());
            loginTextField.setText(usuario.getLogin());
            perfilAcessoTextField.setText(usuario.getPerfilAcesso().name());
            String strUsuarioAtivo;
            if (usuario.isUsuarioAtivo()) {strUsuarioAtivo = "Sim";} else {strUsuarioAtivo = "Não";}
            usuarioAtivoTextField.setText(strUsuarioAtivo);
            buscarPeloIdTextField.setText(String.valueOf(usuario.getId()));
        }        
    }//GEN-LAST:event_buscarPeloLoginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPesquisarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarPeloIdButton;
    private javax.swing.JTextField buscarPeloIdTextField;
    private javax.swing.JButton buscarPeloLoginButton;
    private javax.swing.JTextField buscarPeloLoginTextField;
    private javax.swing.JTextField cpfTextField;
    private javax.swing.JTextField dataNascimentoTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField enderecoTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField loginTextField;
    private javax.swing.JTextField nomeCompletoTextField;
    private javax.swing.JTextField perfilAcessoTextField;
    private javax.swing.JTextField telefoneTextField;
    private javax.swing.JTextField usuarioAtivoTextField;
    // End of variables declaration//GEN-END:variables
}
